---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-rc-node-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "payoneer-ruby.gemspec" }}
          - v1-dependencies-

      - run:
          name: add JUNIT
          command: |
            echo -e "\ngem 'rspec_junit_formatter'" >> Gemfile

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "payoneer-ruby.gemspec" }}

      - run:
          name: run Tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec --format progress \
                              --no-color \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              spec/

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

